loam_interface_gravity:
  ros__parameters:
    use_sim_time: True
    state_estimation_topic: "aft_mapped_to_init"
    registered_scan_topic: "cloud_registered"
    imu_topic: "livox/imu"
    odom_frame: "odom"
    base_frame: "base_footprint"
    lidar_frame: "front_mid360"